### ISSUE TITLE
Event listener identity error

### ISSUE THREAD

**Issue by Andromelus** [cazfletch/node-red-contrib-fabric#1]
Hi.

Using your node, I got an error when deploying.

Indeed, when trying to use admin client, providing a wallet path where admin cert/key already exist (for my pure nodejs code), I get the following error:

![image](https://user-images.githubusercontent.com/10050024/53808156-d3cf7480-3f51-11e9-9689-4874cff836ad.png)

However, when pointing to an empty wallet folder, i get the following error:

![image](https://user-images.githubusercontent.com/10050024/53808200-ec3f8f00-3f51-11e9-8947-054bc03d22d4.png)

Could you provide information on what the node is actually waiting for?

------

ANSWER
If you use identity "admin", you must:
Have a directory called "admin" in the wallet path you provided
Have the admin cert and key inside this directory

**Comment by cazfletch** [comment]
@floriancastelain did you close the issue because you fixed the problem or are you still getting errors?

**Comment by Andromelus** [comment]
Problem fixed, see bottom of original post:


> ANSWER
> If you use identity "admin", you must:
> Have a directory called "admin" in the wallet path you provided
> Have the admin cert and key inside this directory
>
